import { logger } from '@shopgate/engage/core/helpers';

let cached;

/**
 * Gets extension config or empty object on failure.
 * @returns {Object}
 */
function getConfig() {
  if (!cached) {
    try {
      // The file is generated by the SDK from the extension configuration.
      // eslint-disable-next-line global-require
      cached = require('../config.json');
    } catch (e) {
      logger.error('Could not read config.', e);
      cached = {};
    }
  }

  return cached;
}

export default getConfig;
